/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.java_app;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author Yiran Gao 17083214
 */
public class ReservationBooking extends javax.swing.JFrame {

    /**
     * @return the userNameTextField
     */
    public javax.swing.JTextField getUserNameTextField() {
        return userNameTextField;
    }

    /**
     * @param userNameTextField the userNameTextField to set
     */
    public void setUserNameTextField(javax.swing.JTextField userNameTextField) {
        this.userNameTextField = userNameTextField;
    }

    private boolean verifyTable = false;
    private int tableSelected = 0;
    private boolean colour = false;
    private boolean seperate = false;
    private int [] seat = new int[5];
    private boolean isFindATable = false;
    /**
     * Creates new form reservationBooking
     */
    public ReservationBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restaurant = new javax.swing.ButtonGroup();
        tables = new javax.swing.ButtonGroup();
        seperatetables = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        cardNumTextField = new javax.swing.JTextField();
        phoneNumTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tableButton = new javax.swing.JButton();
        cardNumEmail = new javax.swing.JLabel();
        phoneNumLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        restaurantIdLabel = new javax.swing.JLabel();
        restaurantLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        tableLabel = new javax.swing.JLabel();
        tableIDLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameEditLabel = new javax.swing.JLabel();
        allergyLabel = new javax.swing.JLabel();
        allergyGluten = new javax.swing.JRadioButton();
        allergyDairy = new javax.swing.JRadioButton();
        allergyFish = new javax.swing.JRadioButton();
        allergyShellfish = new javax.swing.JRadioButton();
        allergyPeanuts = new javax.swing.JRadioButton();
        allergySoya = new javax.swing.JRadioButton();
        numOfGuestsTextField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        emailTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Table Reservation");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Select Restaurant");

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("restaurant1");
        jRadioButton1.setFocusable(false);
        jRadioButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        restaurant.add(jRadioButton1);
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        jRadioButton2.setText("restaurant2");
        jRadioButton2.setFocusable(false);
        jRadioButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        restaurant.add(jRadioButton2);

        jRadioButton3.setText("restaurant3");
        jRadioButton3.setFocusable(false);
        jRadioButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        restaurant.add(jRadioButton3);

        jRadioButton4.setText("restaurant4");
        jRadioButton4.setToolTipText("");
        jRadioButton4.setFocusable(false);
        jRadioButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        restaurant.add(jRadioButton4);

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        dateTextField.setForeground(new java.awt.Color(153, 153, 153));
        dateTextField.setText("DD-MM-YYYY");
        dateTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateTextFieldMouseClicked(evt);
            }
        });

        jLabel3.setText("Number of Covers:");

        tableButton.setText("Find a table");
        tableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableButtonActionPerformed(evt);
            }
        });

        cardNumEmail.setText("CardNum");

        phoneNumLabel.setText("PhoneNum");

        dateLabel.setText("Date");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Table List:");

        jLabel9.setText("Table1,Seat1");

        jLabel10.setText("Table2,Seat1");

        jLabel11.setText("Table3,Seat1");

        jLabel12.setText("Table4,Seat1");

        jLabel13.setText("Table5,Seat1");

        jRadioButton5.setSelected(true);
        jRadioButton5.setText("jRadioButton5");
        tables.add(jRadioButton5);

        jRadioButton6.setText("jRadioButton6");
        tables.add(jRadioButton6);

        jRadioButton7.setText("jRadioButton7");
        tables.add(jRadioButton7);

        jRadioButton8.setText("jRadioButton8");
        tables.add(jRadioButton8);

        jRadioButton9.setText("jRadioButton9");
        tables.add(jRadioButton9);

        jLabel14.setText("Will you want seperate tables?");

        jRadioButton10.setText("Yes");
        seperatetables.add(jRadioButton10);

        jRadioButton11.setSelected(true);
        jRadioButton11.setText("No");
        seperatetables.add(jRadioButton11);
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        restaurantIdLabel.setText("1");

        restaurantLabel.setText("Restaurant:");

        emailLabel.setText("E-mail");

        tableLabel.setText("Table:");

        tableIDLabel.setText("1");

        nameLabel.setText("Name");

        nameEditLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        nameEditLabel.setText("jLabel21");
        nameEditLabel.setText(mainmenu.fetchUsername());

        allergyLabel.setText("Allergies:");

        allergyGluten.setText("gluten");

        allergyDairy.setText("dairy");

        allergyFish.setText("fish");

        allergyShellfish.setText("shellfish");

        allergyPeanuts.setText("peanuts");

        allergySoya.setText("soya");

        numOfGuestsTextField.setText("jTextField1");

        userNameLabel.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jLabel2)
                                    .addComponent(jRadioButton4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(restaurantLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(restaurantIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(181, 181, 181))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cardNumEmail)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(emailLabel)
                                                .addComponent(nameLabel)
                                                .addComponent(userNameLabel, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGap(25, 25, 25))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(phoneNumLabel)
                                        .addGap(18, 18, 18)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(dateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(allergyGluten)
                                    .addComponent(confirmButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allergyShellfish)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(cancelButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(allergyDairy)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phoneNumTextField)
                                .addComponent(cardNumTextField)
                                .addComponent(tableButton)
                                .addComponent(jLabel14)
                                .addComponent(userNameTextField)
                                .addComponent(nameEditLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(emailTextField1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allergyFish)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(allergyPeanuts)
                                        .addGap(6, 6, 6)
                                        .addComponent(allergySoya))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numOfGuestsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton11))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(allergyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tableLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableIDLabel)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(numOfGuestsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButton10)
                                            .addComponent(jRadioButton11))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(jRadioButton5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButton6)
                                            .addComponent(jLabel10))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dateLabel)
                                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tableButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton8)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton9)
                                    .addComponent(jLabel13))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tableLabel)
                            .addComponent(tableIDLabel))))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantIdLabel)
                    .addComponent(restaurantLabel))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameEditLabel))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNumLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergyGluten)
                    .addComponent(allergyDairy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergyFish)
                    .addComponent(allergyShellfish))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergyPeanuts)
                    .addComponent(allergySoya))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(cancelButton))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        String cardNum = getCardNumTextField().getText();
        String phoneNum = getPhoneNumTextField().getText();
        int max = 0;
        int tableId = 0;
        String email = getEmailTextField().getText();
        String date = getDateTextField().getText();
        String username = getNameEditLabel().getText();
        int userid = mainmenu.fetchUserid();
        int restaurant = Integer.parseInt(getRestaurantIdLabel().getText());
        for(int i = 0;i<5;i++){
            if(max<seat[i]){
                max = seat[i];
                tableId = i+1;
            }
        }
        if((cardNum == "") || (phoneNum == "")){
            JOptionPane.showMessageDialog(null,"Please fill cardNum and phoneNum");
        }else if(isFindATable == false){
            JOptionPane.showMessageDialog(null,"Please find a table first.");
        } else
            if(Integer.parseInt(numOfGuestsTextField.getText())<=max){
            /*
                REQUEST API
                ****makeBooking includes with set selected table state = 0(has booked) and this should be done at server,
                makeBooking(userid,username,restaurant,tableSelected,date,email,cardNum,phoneNum,note);
            */
            JOptionPane.showMessageDialog(null,"Booking successfully, Table ID is " + tableSelected);
            dispose();
            
        }else if(Integer.parseInt(numOfGuestsTextField.getText())>max){
            int covernum = Integer.parseInt(numOfGuestsTextField.getText());
            String tableID = "";
            String str = "";
            for(int i = 0; i < 5 ; i++ ){
                /*
                    REQUEST API
                ****if cover > seat and want to seperate, then we book amount of tables until fit in the cover.
                    if(covernum>0){
                        covernum = covernum - seat[i];
                        makeBooking(userid,username,restaurant,tableSelected,date,email,cardNum,phoneNum,note);
                        str = str + tableID;
                    }
                */
                JOptionPane.showMessageDialog(null,"Booking successfully, Table ID is " + str);
                dispose();
            }
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void tableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableButtonActionPerformed
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("[0-9]*");
        Matcher isNum = pattern.matcher(numOfGuestsTextField.getText());
        if( !isNum.matches() ){
               verifyTable = false;
               JOptionPane.showMessageDialog(null,"Please type in number");
           }else {
           verifyTable = true;
           }
        if(verifyTable == true){
            int cover = 0;
            int restaurant = 0;
            String date = "";
            String dateRegEx="^[0-3]{1}[0-9]{1}-[0-1]{1}[1-2]{1}-[1-9]{1}[0-9]{3}$";
            boolean dateFlag = Pattern.matches(dateRegEx, getDateTextField().getText());
            if (!dateFlag){
                JOptionPane.showMessageDialog(null,"Please type in correct date");
            }else{
               date = getDateTextField().getText();
               cover = Integer.parseInt(numOfGuestsTextField.getText());
               restaurant = Integer.parseInt(getRestaurantIdLabel().getText());
               isFindATable = true;
               // JOptionPane.showMessageDialog(null,"correct" + cover + restaurant);
                /*
                    REQUEST API
                    ****get first 5 empty tables (return number of seats ) on select restaurant:
                    
                    seperate = false;
                    seat = getTableSeat(restaurant,cover,date);
                    jLabel9.setText("Table 1, Seat " + tableSeats[0]);
                    jLabel10.setText("Table 2, Seat " + tableSeats[1]);
                    jLabel11.setText("Table 3, Seat " + tableSeats[2]);
                    jLabel12.setText("Table 4, Seat " + tableSeats[3]);
                    jLabel13.setText("Table 5, Seat " + tableSeats[4]);
                    jRadioButton5.setText(tableSeats[0]);
                    jRadioButton6.setText(tableSeats[1]);
                    jRadioButton7.setText(tableSeats[2]);
                    jRadioButton8.setText(tableSeats[3]);
                    jRadioButton9.setText(tableSeats[4]);
                    ****if cannot find that please return a int array with 0
                    if(tableSeats == 0 && jRadioButton10.isSelected() == true){
                        JOptionPane.showMessageDialog(null,"No valid table for you but we will book seperate tables for you,");
                        seperate = true;
                    }else
                        JOptionPane.showMessageDialog(null,"No valid table for you, Sorry");
                */
            }
        }
    }//GEN-LAST:event_tableButtonActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();//cancel
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        //jLabel15.setText("1");
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void dateTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateTextFieldMouseClicked
        // TODO add your handling code here:
        if(colour==false){
            getDateTextField().setText("");
            getDateTextField().setForeground(Color.BLACK);
            colour = true;
        }
    }//GEN-LAST:event_dateTextFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allergyDairy;
    private javax.swing.JRadioButton allergyFish;
    private javax.swing.JRadioButton allergyGluten;
    private javax.swing.JLabel allergyLabel;
    private javax.swing.JRadioButton allergyPeanuts;
    private javax.swing.JRadioButton allergyShellfish;
    private javax.swing.JRadioButton allergySoya;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cardNumEmail;
    private javax.swing.JTextField cardNumTextField;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JLabel nameEditLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField numOfGuestsTextField;
    private javax.swing.JLabel phoneNumLabel;
    private javax.swing.JTextField phoneNumTextField;
    private javax.swing.ButtonGroup restaurant;
    private javax.swing.JLabel restaurantIdLabel;
    private javax.swing.JLabel restaurantLabel;
    private javax.swing.ButtonGroup seperatetables;
    private javax.swing.JButton tableButton;
    private javax.swing.JLabel tableIDLabel;
    private javax.swing.JLabel tableLabel;
    private javax.swing.ButtonGroup tables;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the allergyDairy
     */
    public JRadioButton getAllergyDairy() {
        return allergyDairy;
    }

    /**
     * @param allergyDairy the allergyDairy to set
     */
    public void setAllergyDairy(javax.swing.JRadioButton allergyDairy) {
        this.allergyDairy = allergyDairy;
    }

    /**
     * @return the allergyFish
     */
    public JRadioButton getAllergyFish() {
        return allergyFish;
    }

    /**
     * @param allergyFish the allergyFish to set
     */
    public void setAllergyFish(javax.swing.JRadioButton allergyFish) {
        this.allergyFish = allergyFish;
    }

    /**
     * @return the allergyGluten
     */
    public JRadioButton getAllergyGluten() {
        return allergyGluten;
    }

    /**
     * @param allergyGluten the allergyGluten to set
     */
    public void setAllergyGluten(javax.swing.JRadioButton allergyGluten) {
        this.allergyGluten = allergyGluten;
    }

    /**
     * @return the allergyPeanuts
     */
    public JRadioButton getAllergyPeanuts() {
        return allergyPeanuts;
    }

    /**
     * @param allergyPeanuts the allergyPeanuts to set
     */
    public void setAllergyPeanuts(javax.swing.JRadioButton allergyPeanuts) {
        this.allergyPeanuts = allergyPeanuts;
    }

    /**
     * @return the allergyShellfish
     */
    public JRadioButton getAllergyShellfish() {
        return allergyShellfish;
    }

    /**
     * @param allergyShellfish the allergyShellfish to set
     */
    public void setAllergyShellfish(javax.swing.JRadioButton allergyShellfish) {
        this.allergyShellfish = allergyShellfish;
    }

    /**
     * @return the allergySoya
     */
    public JRadioButton getAllergySoya() {
        return allergySoya;
    }

    /**
     * @param allergySoya the allergySoya to set
     */
    public void setAllergySoya(javax.swing.JRadioButton allergySoya) {
        this.allergySoya = allergySoya;
    }

    /**
     * @return the cancelButton
     */
    public JButton getCancelButton() {
        return cancelButton;
    }

    /**
     * @param cancelButton the cancelButton to set
     */
    public void setCancelButton(javax.swing.JButton cancelButton) {
        this.cancelButton = cancelButton;
    }

    /**
     * @return the cardNumEmail
     */
    public JLabel getCardNumEmail() {
        return cardNumEmail;
    }

    /**
     * @param cardNumEmail the cardNumEmail to set
     */
    public void setCardNumEmail(javax.swing.JLabel cardNumEmail) {
        this.cardNumEmail = cardNumEmail;
    }

    /**
     * @return the cardNumTextField
     */
    public JTextField getCardNumTextField() {
        return cardNumTextField;
    }

    /**
     * @param cardNumTextField the cardNumTextField to set
     */
    public void setCardNumTextField(javax.swing.JTextField cardNumTextField) {
        this.cardNumTextField = cardNumTextField;
    }

    /**
     * @return the confirmButton
     */
    public javax.swing.JButton getConfirmButton() {
        return confirmButton;
    }

    /**
     * @param confirmButton the confirmButton to set
     */
    public void setConfirmButton(javax.swing.JButton confirmButton) {
        this.confirmButton = confirmButton;
    }

    /**
     * @return the dateTextField
     */
    public JTextField getDateTextField() {
        return dateTextField;
    }

    /**
     * @param dateTextField the dateTextField to set
     */
    public void setDateTextField(javax.swing.JTextField dateTextField) {
        this.dateTextField = dateTextField;
    }

    /**
     * @return the emailTextField
     */
    public JTextField getEmailTextField() {
        return getUserNameTextField();
    }

    /**
     * @param emailTextField the emailTextField to set
     */
    public void setEmailTextField(javax.swing.JTextField emailTextField) {
        this.setUserNameTextField(emailTextField);
    }

    /**
     * @return the nameEditLabel
     */
    public JLabel getNameEditLabel() {
        return nameEditLabel;
    }

    /**
     * @param nameEditLabel the nameEditLabel to set
     */
    public void setNameEditLabel(javax.swing.JLabel nameEditLabel) {
        this.nameEditLabel = nameEditLabel;
    }

    /**
     * @return the phoneNumTextField
     */
    public JTextField getPhoneNumTextField() {
        return phoneNumTextField;
    }

    /**
     * @param phoneNumTextField the phoneNumTextField to set
     */
    public void setPhoneNumTextField(javax.swing.JTextField phoneNumTextField) {
        this.phoneNumTextField = phoneNumTextField;
    }

    /**
     * @return the restaurantIdLabel
     */
    public JLabel getRestaurantIdLabel() {
        return restaurantIdLabel;
    }

    /**
     * @param restaurantIdLabel the restaurantIdLabel to set
     */
    public void setRestaurantIdLabel(javax.swing.JLabel restaurantIdLabel) {
        this.restaurantIdLabel = restaurantIdLabel;
    }

    /**
     * @return the tableButton
     */
    public JButton getTableButton() {
        return tableButton;
    }

    /**
     * @param tableButton the tableButton to set
     */
    public void setTableButton(javax.swing.JButton tableButton) {
        this.tableButton = tableButton;
    }

    /**
     * @return the tableIDLabel
     */
    public JLabel getTableIDLabel() {
        return tableIDLabel;
    }

    /**
     * @param tableIDLabel the tableIDLabel to set
     */
    public void setTableIDLabel(javax.swing.JLabel tableIDLabel) {
        this.tableIDLabel = tableIDLabel;
    }

    /**
     * @return the numOfGuestsTextField
     */
    public JTextField getNumOfGuestsTextField() {
        return numOfGuestsTextField;
    }

    /**
     * @param jTextField1 the numOfGuestsTextField to set
     */
    public void setNumOfGuestsTextField(javax.swing.JTextField numOfGuestsTextField) {
        this.numOfGuestsTextField = numOfGuestsTextField;
    }
}
