package view;

import java.util.Calendar;
import controller.feedbackController;
import javax.swing.AbstractButton;

/**
 *
 * @author Yiran Gao - 17083214
 */

public class FeedBackView extends javax.swing.JFrame {

    /**
     * Creates new form FeedBackView
     */
    public FeedBackView() {
        initComponents();
    }
    
    private feedbackController feedback;
    
    public FeedBackView(feedbackController aFeedback)
    {
        feedback = aFeedback;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        waiterMarkButtonGroup = new javax.swing.ButtonGroup();
        waiterMarkButtonGroup.add(waiterMarkButton1);
        waiterMarkButtonGroup.add(waiterMarkButton2);
        waiterMarkButtonGroup.add(waiterMarkButton3);
        waiterMarkButtonGroup.add(waiterMarkButton4);
        waiterMarkButtonGroup.add(waiterMarkButton5);
        titleTextLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        waiterLabel = new javax.swing.JLabel();
        waiterMarkButton1 = new javax.swing.JRadioButton();
        waiterMarkButton2 = new javax.swing.JRadioButton();
        waiterMarkButton3 = new javax.swing.JRadioButton();
        waiterMarkButton4 = new javax.swing.JRadioButton();
        waiterMarkButton5 = new javax.swing.JRadioButton();
        waiterScoreLabel = new javax.swing.JLabel();
        fronthouseLabel = new javax.swing.JLabel();
        frontScoreLabel = new javax.swing.JLabel();
        tableIDLabel = new javax.swing.JLabel();
        Confirm = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        reservationID = new javax.swing.JTextField();

        waiterMarkButtonGroup.add(waiterMarkButton1);
        waiterMarkButtonGroup.add(waiterMarkButton2);
        waiterMarkButtonGroup.add(waiterMarkButton3);
        waiterMarkButtonGroup.add(waiterMarkButton4);
        waiterMarkButtonGroup.add(waiterMarkButton5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titleTextLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titleTextLabel.setText("Your Opinion, Our Business!");

        usernameLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        usernameLabel.setText("user");

        waiterLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        waiterLabel.setText("Feedback Mark:");

        waiterMarkButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waiterMarkButton1ActionPerformed(evt);
            }
        });

        waiterMarkButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waiterMarkButton2ActionPerformed(evt);
            }
        });

        waiterMarkButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waiterMarkButton3ActionPerformed(evt);
            }
        });

        waiterMarkButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waiterMarkButton4ActionPerformed(evt);
            }
        });

        waiterMarkButton5.setSelected(true);
        waiterMarkButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waiterMarkButton5ActionPerformed(evt);
            }
        });

        waiterScoreLabel.setText("Score");

        fronthouseLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        fronthouseLabel.setText("Reservation ID:");

        frontScoreLabel.setText("Score");

        tableIDLabel.setText("jLabel1");

        Confirm.setText("Confirm");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        dateLabel.setText("currentdate");
        Calendar c = Calendar.getInstance();
 
 int year = c.get(Calendar.YEAR);  
 
 int month = c.get(Calendar.MONTH);   
 
 int date = c.get(Calendar.DATE);      
 
 dateLabel.setText(year + "/" + (month+1) + "/" + date);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(waiterLabel)
                                            .addGap(35, 35, 35)
                                            .addComponent(waiterMarkButton1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(fronthouseLabel)
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(waiterMarkButton2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(waiterMarkButton3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(waiterMarkButton4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(waiterMarkButton5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(waiterScoreLabel))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(173, 173, 173)
                                            .addComponent(tableIDLabel))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(reservationID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                            .addComponent(frontScoreLabel))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Confirm)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cancel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(usernameLabel)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addComponent(titleTextLabel))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titleTextLabel)
                .addGap(13, 13, 13)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameLabel)
                            .addComponent(tableIDLabel))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(waiterLabel)
                                .addComponent(waiterMarkButton1)
                                .addComponent(waiterMarkButton2))
                            .addComponent(waiterMarkButton4)
                            .addComponent(waiterMarkButton5)
                            .addComponent(waiterMarkButton3)))
                    .addComponent(waiterScoreLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fronthouseLabel)
                            .addComponent(reservationID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))
                    .addComponent(frontScoreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirm)
                    .addComponent(Cancel))
                .addGap(41, 41, 41))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void waiterMarkButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waiterMarkButton3ActionPerformed
        // TODO add your handling code here:
                waiterScoreLabel.setText("3");
    }//GEN-LAST:event_waiterMarkButton3ActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void waiterMarkButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waiterMarkButton1ActionPerformed
        // TODO add your handling code here:
        waiterScoreLabel.setText("1");
    }//GEN-LAST:event_waiterMarkButton1ActionPerformed

    private void waiterMarkButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waiterMarkButton2ActionPerformed
        waiterScoreLabel.setText("2");        // TODO add your handling code here:
    }//GEN-LAST:event_waiterMarkButton2ActionPerformed

    private void waiterMarkButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waiterMarkButton4ActionPerformed
        // TODO add your handling code here:
                waiterScoreLabel.setText("4");
    }//GEN-LAST:event_waiterMarkButton4ActionPerformed

    private void waiterMarkButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waiterMarkButton5ActionPerformed
        // TODO add your handling code here:
                waiterScoreLabel.setText("5");
    }//GEN-LAST:event_waiterMarkButton5ActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        // TODO add your handling code here:
        feedback.submitFeedback(Integer.parseInt(waiterScoreLabel.getText()), Integer.parseInt(reservationID.getText()));
    }//GEN-LAST:event_ConfirmActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Confirm;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel frontScoreLabel;
    private javax.swing.JLabel fronthouseLabel;
    private javax.swing.JTextField reservationID;
    private javax.swing.JLabel tableIDLabel;
    private javax.swing.JLabel titleTextLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel waiterLabel;
    private javax.swing.JRadioButton waiterMarkButton1;
    private javax.swing.JRadioButton waiterMarkButton2;
    private javax.swing.JRadioButton waiterMarkButton3;
    private javax.swing.JRadioButton waiterMarkButton4;
    private javax.swing.JRadioButton waiterMarkButton5;
    private javax.swing.ButtonGroup waiterMarkButtonGroup;
    private javax.swing.JLabel waiterScoreLabel;
    // End of variables declaration//GEN-END:variables

}
