package view;

import java.util.Calendar;
import controller.FeedbackController;

public class FeedBackView1 extends javax.swing.JFrame {

    /**
     * Creates new form FeedBackView
     */
    public FeedBackView1() {
        initComponents();
    }
    
    private FeedbackController feedback;
    
    public FeedBackView1(FeedbackController aFeedback)
    {
        feedback = aFeedback;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        waiterMarkButtonGroup = new javax.swing.ButtonGroup();
        waiterMarkButtonGroup.add(feedbackMarkButton1);
        waiterMarkButtonGroup.add(feedbackMarkButton2);
        waiterMarkButtonGroup.add(feedbackMarkButton3);
        waiterMarkButtonGroup.add(feedbackMarkButton4);
        waiterMarkButtonGroup.add(feedbackMarkButton5);

        titleTextLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        feedbackMark = new javax.swing.JLabel();
        feedbackMarkButton1 = new javax.swing.JRadioButton();
        feedbackMarkButton2 = new javax.swing.JRadioButton();
        feedbackMarkButton3 = new javax.swing.JRadioButton();
        feedbackMarkButton4 = new javax.swing.JRadioButton();
        feedbackMarkButton5 = new javax.swing.JRadioButton();
        waiterScoreLabel = new javax.swing.JLabel();
        tableIDLabel = new javax.swing.JLabel();
        Confirm = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblReservationID = new javax.swing.JLabel();
        reservationID = new javax.swing.JTextField();

        waiterMarkButtonGroup.add(feedbackMarkButton1);
        waiterMarkButtonGroup.add(feedbackMarkButton2);
        waiterMarkButtonGroup.add(feedbackMarkButton3);
        waiterMarkButtonGroup.add(feedbackMarkButton4);
        waiterMarkButtonGroup.add(feedbackMarkButton5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titleTextLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titleTextLabel.setText("Your Opinion, Our Business!");

        usernameLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        usernameLabel.setText("user");

        feedbackMark.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        feedbackMark.setText("Feedback Mark:");

        feedbackMarkButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackMarkButton1ActionPerformed(evt);
            }
        });

        feedbackMarkButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackMarkButton2ActionPerformed(evt);
            }
        });

        feedbackMarkButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackMarkButton3ActionPerformed(evt);
            }
        });

        feedbackMarkButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackMarkButton4ActionPerformed(evt);
            }
        });

        feedbackMarkButton5.setSelected(true);
        feedbackMarkButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackMarkButton5ActionPerformed(evt);
            }
        });

        waiterScoreLabel.setText("Score");

        tableIDLabel.setText("jLabel1");

        Confirm.setText("Confirm");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        dateLabel.setText("currentdate");
        Calendar c = Calendar.getInstance();
 
 int year = c.get(Calendar.YEAR);  
 
 int month = c.get(Calendar.MONTH);   
 
 int date = c.get(Calendar.DATE);      
 
 dateLabel.setText(year + "/" + (month+1) + "/" + date);

        lblReservationID.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        lblReservationID.setText("Reservation ID:");

        reservationID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addComponent(titleTextLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(Confirm)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cancel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(feedbackMark)
                                    .addGap(41, 41, 41)
                                    .addComponent(feedbackMarkButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(feedbackMarkButton2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(feedbackMarkButton3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(feedbackMarkButton4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(feedbackMarkButton5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(waiterScoreLabel))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(173, 173, 173)
                                            .addComponent(tableIDLabel))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(usernameLabel))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblReservationID)
                                            .addGap(18, 18, 18)
                                            .addComponent(reservationID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titleTextLabel)
                .addGap(13, 13, 13)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameLabel)
                            .addComponent(tableIDLabel))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(feedbackMark)
                                .addComponent(feedbackMarkButton1)
                                .addComponent(feedbackMarkButton2))
                            .addComponent(feedbackMarkButton4)
                            .addComponent(feedbackMarkButton5)
                            .addComponent(feedbackMarkButton3)))
                    .addComponent(waiterScoreLabel))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReservationID)
                    .addComponent(reservationID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirm)
                    .addComponent(Cancel))
                .addGap(41, 41, 41))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void feedbackMarkButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
                waiterScoreLabel.setText("3");
    }                                                   

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        dispose();
    }                                      

    private void feedbackMarkButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        waiterScoreLabel.setText("1");
    }                                                   

    private void feedbackMarkButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        waiterScoreLabel.setText("2");        // TODO add your handling code here:
    }                                                   

    private void feedbackMarkButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
                waiterScoreLabel.setText("4");
    }                                                   

    private void feedbackMarkButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
                waiterScoreLabel.setText("5");
    }                                                   

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {                                        

        //lblUserid.setText(Integer.toString(staff.getUserID()));
        feedback.submitFeedback(Integer.parseInt(waiterScoreLabel.getText()), Integer.parseInt(reservationID.getText()));
    }                                       

    private void reservationIDActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             



    // Variables declaration - do not modify                     
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Confirm;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel feedbackMark;
    private javax.swing.JRadioButton feedbackMarkButton1;
    private javax.swing.JRadioButton feedbackMarkButton2;
    private javax.swing.JRadioButton feedbackMarkButton3;
    private javax.swing.JRadioButton feedbackMarkButton4;
    private javax.swing.JRadioButton feedbackMarkButton5;
    private javax.swing.ButtonGroup frontMarkButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblReservationID;
    private javax.swing.JTextField reservationID;
    private javax.swing.JLabel tableIDLabel;
    private javax.swing.JLabel titleTextLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.ButtonGroup waiterMarkButtonGroup;
    private javax.swing.JLabel waiterScoreLabel;
    // End of variables declaration                   
}

