/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.StaffBean;
import javax.swing.JButton;

/**
 *
 * @author Yiran Gao - 17083214
 */
public class MainmenuView extends javax.swing.JFrame {
    
    private StaffBean staff;
   /* private static String name = Team10_ProjectClient.fetchUsername(); 
    private static int id = Team10_ProjectClient.fetchUserid();
    private static int type = Team10_ProjectClient.fetchUsertype();*/
    /**
     * Creates new form mainmenu
     */
    public MainmenuView(StaffBean aStaff) {
        staff = aStaff;
      /*name = Team10_ProjectClient.fetchUsername();
      id = Team10_ProjectClient.fetchUserid();
      type = Team10_ProjectClient.fetchUsertype();*/
      //JOptionPane.showMessageDialog(null,name + id);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        createReservationButton = new javax.swing.JButton();
        cancelReservationButton = new javax.swing.JButton();
        modifyReservationButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        profileButton = new javax.swing.JButton();
        createCustomerButton1 = new javax.swing.JButton();
        modifyCustomerButton1 = new javax.swing.JButton();
        deleteCustomerButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        welcomeLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        welcomeLabel.setText("Welcome!");

        createReservationButton.setText("Create Reservation");

        cancelReservationButton.setText("Cancel Reservation");

        modifyReservationButton.setText("Modify Reservation");

        usernameLabel.setText(staff.getUserName());
        /* SeanHelpMe 
        the username label needs text for username.
        usernameLabel.setText(fetchUsername(String username));
        */

        profileButton.setText("Profile");

        createCustomerButton1.setText("Create Customer");

        modifyCustomerButton1.setText("Modify Customer");

        deleteCustomerButton1.setText("Delete Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profileButton)
                            .addComponent(usernameLabel))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteCustomerButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelReservationButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(modifyCustomerButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modifyReservationButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(createCustomerButton1)
                                .addGap(102, 102, 102)
                                .addComponent(createReservationButton)))
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profileButton)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createReservationButton)
                    .addComponent(createCustomerButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyReservationButton)
                    .addComponent(modifyCustomerButton1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelReservationButton)
                    .addComponent(deleteCustomerButton1))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  /*  public static int fetchUserid() {
         return id;
     }

     public static String fetchUsername() {
         return name;
     }
     public static int fetchUsertype() {
         return type;
     }*/
    /**
     * @author Yiran Gao - 17083214
     * @param args the command line arguments
     */
    public static void main() {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainmenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainmenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainmenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainmenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new MainmenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelReservationButton;
    private javax.swing.JButton createCustomerButton1;
    private javax.swing.JButton createReservationButton;
    private javax.swing.JButton deleteCustomerButton1;
    private javax.swing.JButton modifyCustomerButton1;
    private javax.swing.JButton modifyReservationButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the profileButton
     */
    public JButton getUserProfileButton() {
        return profileButton;
    }
    
    /**
     * @return the cancelReservationButton
     */
    public JButton getCancelReservationButton() {
        return cancelReservationButton;
    }

    /**
     * @return the createReservationButton
     */
    public JButton getCreateReservationButton() {
        return createReservationButton;
    }

    /**
     * @return the modifyReservationButton
     */
    public JButton getModifyReservationButton() {
        return modifyReservationButton;
    }
    
    /**
     * @return the createCustomerButton1
     */
    public JButton getCreateCustomerButton() {
        return createCustomerButton1;
    }

    /**
     * @return the modifyCustomerButton1
     */
    public JButton getModifyCustomerButton() {
        return modifyCustomerButton1;
    }

    /**
     * @return the deleteCustomerButton1
     */
    public JButton getDeleteCustomerButton() {
        return deleteCustomerButton1;
    }
    
}
