/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.StaffBean;
import javax.swing.JButton;

/**
 *
 * @author Yiran Gao - 17083214
 */
public class MainmenuView extends javax.swing.JFrame {
    
    private StaffBean staff;
    /**
     * Creates new form mainmenu
     */
    public MainmenuView(StaffBean aStaff) {
        staff = aStaff;
        initComponents();
        setVisible(true);
        if(staff.getUserType() == 2) {
            createStaffButton.setVisible(false);
            modifyStaffButton.setVisible(false);
            deleteStaffButton.setVisible(false);
            checkInButton.setVisible(false);
            
        } else if(staff.getUserType() == 3) {
            createStaffButton.setVisible(false);
            modifyStaffButton.setVisible(false);
            deleteStaffButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        createReservationButton = new javax.swing.JButton();
        cancelReservationButton = new javax.swing.JButton();
        modifyReservationButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        profileButton = new javax.swing.JButton();
        createCustomerButton = new javax.swing.JButton();
        modifyCustomerButton = new javax.swing.JButton();
        deleteCustomerButton = new javax.swing.JButton();
        checkInButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        createStaffButton = new javax.swing.JButton();
        modifyStaffButton = new javax.swing.JButton();
        deleteStaffButton = new javax.swing.JButton();
        addFeedbackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        welcomeLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        welcomeLabel.setText("Welcome!");

        createReservationButton.setText("Create Reservation");

        cancelReservationButton.setText("Cancel Reservation");

        modifyReservationButton.setText("Modify Reservation");
        modifyReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyReservationButtonActionPerformed(evt);
            }
        });

        usernameLabel.setText(staff.getUserName());
        /* SeanHelpMe 
        the username label needs text for username.
        usernameLabel.setText(fetchUsername(String username));
        */

        profileButton.setText("Profile");

        createCustomerButton.setText("Create Customer");

        modifyCustomerButton.setText("Modify Customer");

        deleteCustomerButton.setText("Delete Customer");

        checkInButton.setText("Check In");

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        createStaffButton.setText("Create Staff");

        modifyStaffButton.setText("Modify Staff");

        deleteStaffButton.setText("Delete Staff");

        addFeedbackButton.setText("Add Feedback");
        addFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFeedbackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addGap(305, 305, 305))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profileButton)
                            .addComponent(usernameLabel))
                        .addGap(52, 52, 52))))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkInButton)
                        .addGap(56, 56, 56)
                        .addComponent(logOutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addFeedbackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteCustomerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteStaffButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelReservationButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modifyCustomerButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modifyStaffButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createCustomerButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createStaffButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modifyReservationButton)
                            .addComponent(createReservationButton))))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profileButton)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createReservationButton)
                    .addComponent(createCustomerButton)
                    .addComponent(createStaffButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyReservationButton)
                    .addComponent(modifyCustomerButton)
                    .addComponent(modifyStaffButton))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelReservationButton)
                    .addComponent(deleteCustomerButton)
                    .addComponent(deleteStaffButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInButton)
                    .addComponent(logOutButton)
                    .addComponent(addFeedbackButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modifyReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyReservationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyReservationButtonActionPerformed

    private void addFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFeedbackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFeedbackButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutButtonActionPerformed
  /*  public static int fetchUserid() {
         return id;
     }

     public static String fetchUsername() {
         return name;
     }
     public static int fetchUsertype() {
         return type;
     }*/
    /**
     * @author Yiran Gao - 17083214
     * @param args the command line arguments
     */
    public static void main() {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainmenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainmenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainmenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainmenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new MainmenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFeedbackButton;
    private javax.swing.JButton cancelReservationButton;
    private javax.swing.JButton checkInButton;
    private javax.swing.JButton createCustomerButton;
    private javax.swing.JButton createReservationButton;
    private javax.swing.JButton createStaffButton;
    private javax.swing.JButton deleteCustomerButton;
    private javax.swing.JButton deleteStaffButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton modifyCustomerButton;
    private javax.swing.JButton modifyReservationButton;
    private javax.swing.JButton modifyStaffButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the profileButton
     */
    public JButton getUserProfileButton() {
        return profileButton;
    }
    
    /**
     * @return the cancelReservationButton
     */
    public JButton getCancelReservationButton() {
        return cancelReservationButton;
    }

    /**
     * @return the createReservationButton
     */
    public JButton getCreateReservationButton() {
        return createReservationButton;
    }

    /**
     * @return the modifyReservationButton
     */
    public JButton getModifyReservationButton() {
        return modifyReservationButton;
    }
    
    /**
     * @return the createCustomerButton
     */
    public JButton getCreateCustomerButton() {
        return createCustomerButton;
    }

    /**
     * @return the modifyCustomerButton
     */
    public JButton getModifyCustomerButton() {
        return modifyCustomerButton;
    }

    /**
     * @return the deleteCustomerButton
     */
    public JButton getDeleteCustomerButton() {
        return deleteCustomerButton;
    }
    
    /**
     * @return the createStaffButton
     */
    public JButton getCreateStaffButton() {
        return createStaffButton;
    }

    /**
     * @return the modifyCustomerButton
     */
    public JButton getModifyStaffButton() {
        return modifyStaffButton;
    }

    /**
     * @return the deleteStaffButton
     */
    public JButton getDeleteStaffButton() {
        return deleteStaffButton;
    }
    
    /**
     * @return the checkOutButton
     */
    public JButton getCheckInButton() {
        return checkInButton;
    }

    /**
     * @return the checkOutButton
     */
    public JButton getLogOutButton() {
        return logOutButton;
    }

    /**
     * @return the addFeedbackButton
     */
    public JButton getAddFeedbackButton() {
        return addFeedbackButton;
    }
}
