/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author Yiran Gao 17083214
 */
public class ReservationBookingView extends javax.swing.JFrame {

    /**
     * @return the userNameTextField
     */
//    public javax.swing.JLabel getUserNameLabel() {
//        return userNameTextField;
//    }
    public javax.swing.JLabel getUserNameLabel() {
        return usernameLabel;
    }

    /**
     * @param userNameTextField the userNameTextField to set
     */
//    public void setUserNameTextField(javax.swing.JTextField userNameTextField) {
//        this.userNameTextField = userNameTextField;
//    }
        public void setUserNameTextField(javax.swing.JLabel usernameLabel) {
        this.usernameLabel = usernameLabel;
    }

    private boolean verifyTable = false;
    private int tableSelected = 0;
    private boolean colour = false;
    private boolean seperate = false;
    private int [] seat = new int[5];
    private boolean isFindATable = false;
    /**
     * Creates new form reservationBooking
     */
    public ReservationBookingView() {
        initComponents();
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restaurant = new javax.swing.ButtonGroup();
        tables = new javax.swing.ButtonGroup();
        seperatetables = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        dateTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tableButton = new javax.swing.JButton();
        cardnumTextEmail = new javax.swing.JLabel();
        phonenumTextLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        emailTextLabel = new javax.swing.JLabel();
        nameTextLabel = new javax.swing.JLabel();
        nameEditLabel = new javax.swing.JLabel();
        allergyLabel = new javax.swing.JLabel();
        allergyGluten = new javax.swing.JRadioButton();
        allergyDairy = new javax.swing.JRadioButton();
        allergyFish = new javax.swing.JRadioButton();
        allergyShellfish = new javax.swing.JRadioButton();
        allergyPeanuts = new javax.swing.JRadioButton();
        allergySoya = new javax.swing.JRadioButton();
        numOfGuestsTextField = new javax.swing.JTextField();
        userNameTextLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        cardnumLabel = new javax.swing.JLabel();
        phonenumLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        restaurantList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Table Reservation");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Select Restaurant");

        confirmButton.setText("Confirm");

        cancelButton.setText("Cancel");

        dateTextField.setForeground(new java.awt.Color(153, 153, 153));
        dateTextField.setText("DD-MM-YYYY");
        dateTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateTextFieldMouseClicked(evt);
            }
        });

        jLabel3.setText("Number of Covers:");

        tableButton.setText("Find a table");

        cardnumTextEmail.setText("CardNum");

        phonenumTextLabel.setText("PhoneNum");

        dateLabel.setText("Date");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Table List:");

        jLabel14.setText("Will you want seperate tables?");

        jRadioButton10.setText("Yes");
        seperatetables.add(jRadioButton10);

        jRadioButton11.setSelected(true);
        jRadioButton11.setText("No");
        seperatetables.add(jRadioButton11);

        emailTextLabel.setText("E-mail");

        nameTextLabel.setText("Name");

        nameEditLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        nameEditLabel.setText("jLabel21");

        allergyLabel.setText("Allergies:");

        allergyGluten.setText("gluten");

        allergyDairy.setText("dairy");

        allergyFish.setText("fish");

        allergyShellfish.setText("shellfish");

        allergyPeanuts.setText("peanuts");

        allergySoya.setText("soya");

        userNameTextLabel.setText("Username");

        usernameLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        usernameLabel.setText("jLabel4");

        emailLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        emailLabel.setText("jLabel5");

        cardnumLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        cardnumLabel.setText("jLabel6");

        phonenumLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        phonenumLabel.setText("jLabel7");

        tabelList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(tabelList);

        restaurantList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(restaurantList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardnumTextEmail)
                            .addComponent(userNameTextLabel)
                            .addComponent(nameTextLabel)
                            .addComponent(emailTextLabel)
                            .addComponent(phonenumTextLabel))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allergyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(dateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(allergyGluten)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(cancelButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(allergyDairy)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(allergyPeanuts)
                                            .addComponent(allergyFish))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(allergyShellfish)
                                            .addComponent(allergySoya)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton11))
                                            .addComponent(numOfGuestsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(usernameLabel)
                                            .addComponent(nameEditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cardnumLabel)
                                            .addComponent(emailLabel)
                                            .addComponent(phonenumLabel)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton11))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel))
                        .addGap(18, 18, 18)
                        .addComponent(tableButton)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTextLabel)
                            .addComponent(nameEditLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameTextLabel)
                            .addComponent(usernameLabel))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTextLabel)
                            .addComponent(emailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cardnumTextEmail)
                            .addComponent(cardnumLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phonenumTextLabel)
                            .addComponent(phonenumLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(numOfGuestsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergyGluten)
                    .addComponent(allergyDairy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergyFish)
                    .addComponent(allergyShellfish))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergyPeanuts)
                    .addComponent(allergySoya))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(cancelButton))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dateTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateTextFieldMouseClicked
        // TODO add your handling code here:
        dateTextField.setText("");
        dateTextField.setForeground(Color.BLACK);
    }//GEN-LAST:event_dateTextFieldMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allergyDairy;
    private javax.swing.JRadioButton allergyFish;
    private javax.swing.JRadioButton allergyGluten;
    private javax.swing.JLabel allergyLabel;
    private javax.swing.JRadioButton allergyPeanuts;
    private javax.swing.JRadioButton allergyShellfish;
    private javax.swing.JRadioButton allergySoya;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cardnumLabel;
    private javax.swing.JLabel cardnumTextEmail;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailTextLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nameEditLabel;
    private javax.swing.JLabel nameTextLabel;
    private javax.swing.JTextField numOfGuestsTextField;
    private javax.swing.JLabel phonenumLabel;
    private javax.swing.JLabel phonenumTextLabel;
    private javax.swing.ButtonGroup restaurant;
    private javax.swing.JList<String> restaurantList;
    private javax.swing.ButtonGroup seperatetables;
    private javax.swing.JList<String> tabelList;
    private javax.swing.JButton tableButton;
    private javax.swing.ButtonGroup tables;
    private javax.swing.JLabel userNameTextLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the allergyDairy
     */
    public JRadioButton getAllergyDairy() {
        return allergyDairy;
    }

    /**
     * @param allergyDairy the allergyDairy to set
     */
    public void setAllergyDairy(javax.swing.JRadioButton allergyDairy) {
        this.allergyDairy = allergyDairy;
    }

    /**
     * @return the allergyFish
     */
    public JRadioButton getAllergyFish() {
        return allergyFish;
    }

    /**
     * @param allergyFish the allergyFish to set
     */
    public void setAllergyFish(javax.swing.JRadioButton allergyFish) {
        this.allergyFish = allergyFish;
    }

    /**
     * @return the allergyGluten
     */
    public JRadioButton getAllergyGluten() {
        return allergyGluten;
    }

    /**
     * @param allergyGluten the allergyGluten to set
     */
    public void setAllergyGluten(javax.swing.JRadioButton allergyGluten) {
        this.allergyGluten = allergyGluten;
    }

    /**
     * @return the allergyPeanuts
     */
    public JRadioButton getAllergyPeanuts() {
        return allergyPeanuts;
    }

    /**
     * @param allergyPeanuts the allergyPeanuts to set
     */
    public void setAllergyPeanuts(javax.swing.JRadioButton allergyPeanuts) {
        this.allergyPeanuts = allergyPeanuts;
    }

    /**
     * @return the allergyShellfish
     */
    public JRadioButton getAllergyShellfish() {
        return allergyShellfish;
    }

    /**
     * @param allergyShellfish the allergyShellfish to set
     */
    public void setAllergyShellfish(javax.swing.JRadioButton allergyShellfish) {
        this.allergyShellfish = allergyShellfish;
    }

    /**
     * @return the allergySoya
     */
    public JRadioButton getAllergySoya() {
        return allergySoya;
    }

    /**
     * @param allergySoya the allergySoya to set
     */
    public void setAllergySoya(javax.swing.JRadioButton allergySoya) {
        this.allergySoya = allergySoya;
    }

    /**
     * @return the cancelButton
     */
    public JButton getCancelButton() {
        return cancelButton;
    }

    /**
     * @param cancelButton the cancelButton to set
     */
    public void setCancelButton(javax.swing.JButton cancelButton) {
        this.cancelButton = cancelButton;
    }

    /**
     * @return the cardNumEmail
     */
    public JLabel getCardNumEmail() {
        return cardnumTextEmail;
    }

    /**
     * @param cardNumEmail the cardNumEmail to set
     */
    public void setCardNumEmail(javax.swing.JLabel cardNumEmail) {
        this.cardnumTextEmail = cardNumEmail;
    }

    /**
     * @return the cardNumTextField
     */
//    public JTextField getCardNumTextField() {
//        return cardNumTextField;
//    }
    public JLabel getCardNumLabel() {
        return cardnumLabel;
    }

    /**
     * @param cardNumTextField the cardNumTextField to set
     */
//    public void setCardNumTextField(javax.swing.JTextField cardNumTextField) {
//        this.cardNumTextField = cardNumTextField;
//    }
    public void setCardNumLabel(javax.swing.JLabel cardnumLabel) {
        this.cardnumLabel = cardnumLabel;
    }

    /**
     * @return the confirmButton
     */
    public javax.swing.JButton getConfirmButton() {
        return confirmButton;
    }

    /**
     * @param confirmButton the confirmButton to set
     */
    public void setConfirmButton(javax.swing.JButton confirmButton) {
        this.confirmButton = confirmButton;
    }

    /**
     * @return the dateTextField
     */
    public JTextField getDateTextField() {
        return dateTextField;
    }

    /**
     * @param dateTextField the dateTextField to set
     */
    public void setDateTextField(javax.swing.JTextField dateTextField) {
        this.dateTextField = dateTextField;
    }

    /**
     * @return the emailTextField
     */
//    public JTextField getEmailTextField() {
//        return getUserNameTextField();
//    }
      public JLabel getEmailLabel() {
        return emailLabel;
    }

    /**
     * @param emailTextField the emailTextField to set
     */
//    public void setEmailTextField(javax.swing.JTextField emailTextField) {
//        this.setUserNameTextField(emailTextField);
//    }
    public void setEmailLabel(javax.swing.JLabel emailLabel) {
        this.setEmailLabel(emailLabel);
    }

    /**
     * @return the nameEditLabel
     */
    public JLabel getNameEditLabel() {
        return nameEditLabel;
    }

    /**
     * @param nameEditLabel the nameEditLabel to set
     */
    public void setNameEditLabel(javax.swing.JLabel nameEditLabel) {
        this.nameEditLabel = nameEditLabel;
    }

    /**
     * @return the phoneNumTextField
     */
    public JLabel getPhoneNumLabel() {
        return phonenumLabel;
    }

    /**
     * @param phoneNumTextField the phoneNumTextField to set
     */
//    public void setPhoneNumTextField(javax.swing.JTextField phoneNumTextField) {
//        this.phoneNumTextField = phoneNumTextField;
//    }
    public void setPhoneNumTextField(javax.swing.JLabel phonenumLabel) {
        this.phonenumLabel = phonenumLabel;
    }


    /**
     * @return the restaurantIdLabel
     */
//    public JLabel getRestaurantIdLabel() {
//        return restaurantIdLabel;
//    }

    /**
     * @param restaurantIdLabel the restaurantIdLabel to set
     */
//    public void setRestaurantIdLabel(javax.swing.JLabel restaurantIdLabel) {
//        this.restaurantIdLabel = restaurantIdLabel;
//    }

    /**
     * @return the tableButton
     */
    public JButton getTableButton() {
        return tableButton;
    }

    /**
     * @param tableButton the tableButton to set
     */
    public void setTableButton(javax.swing.JButton tableButton) {
        this.tableButton = tableButton;
    }

    /**
     * @return the tableIDLabel
     */
//    public JLabel getTableIDLabel() {
//        return tableIDLabel;
//    }

    /**
     * @param tableIDLabel the tableIDLabel to set
     */
//    public void setTableIDLabel(javax.swing.JLabel tableIDLabel) {
//        this.tableIDLabel = tableIDLabel;
//    }

    /**
     * @return the numOfGuestsTextField
     */
    public JTextField getNumOfGuestsTextField() {
        return numOfGuestsTextField;
    }

    /**
     * @param numOfGuestsTextField
     */
    public void setNumOfGuestsTextField(javax.swing.JTextField numOfGuestsTextField) {
        this.numOfGuestsTextField = numOfGuestsTextField;
    }
}
