/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author Yiran Gao 17083214
 */
public class ReservationBookingView extends javax.swing.JFrame {

    /**
     * @return the userNameTextField
     */
//    public javax.swing.JLabel getUserNameLabel() {
//        return userNameTextField;
//    }
    public javax.swing.JLabel getUserNameLabel() {
        return usernameLabel;
    }

    /**
     * @param userNameTextField the userNameTextField to set
     */
//    public void setUserNameTextField(javax.swing.JTextField userNameTextField) {
//        this.userNameTextField = userNameTextField;
//    }
        public void setUserNameTextField(javax.swing.JLabel usernameLabel) {
        this.usernameLabel = usernameLabel;
    }

    private boolean verifyTable = false;
    private int tableSelected = 0;
    private boolean colour = false;
    private boolean seperate = false;
    private int [] seat = new int[5];
    private boolean isFindATable = false;
    private boolean isFindATime = false;
    /**
     * Creates new form reservationBooking
     */
    public ReservationBookingView() {
        initComponents();
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restaurant = new javax.swing.ButtonGroup();
        tables = new javax.swing.ButtonGroup();
        seperatetables = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        restaurantTextLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tableButton = new javax.swing.JButton();
        cardnumTextEmail = new javax.swing.JLabel();
        phonenumTextLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        emailTextLabel = new javax.swing.JLabel();
        nameTextLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        allergyLabel = new javax.swing.JLabel();
        allergyGluten = new javax.swing.JRadioButton();
        allergyDairy = new javax.swing.JRadioButton();
        allergyFish = new javax.swing.JRadioButton();
        allergyShellfish = new javax.swing.JRadioButton();
        allergyPeanuts = new javax.swing.JRadioButton();
        allergySoya = new javax.swing.JRadioButton();
        numOfGuestsTextField = new javax.swing.JTextField();
        userNameTextLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        cardnumLabel = new javax.swing.JLabel();
        phonenumLabel = new javax.swing.JLabel();
        restaurantLabel = new javax.swing.JLabel();
        loyaltyTextLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableList = new javax.swing.JList<>();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        loyaltyLabel = new javax.swing.JLabel();
        discountTextLabel = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        timeslotList = new javax.swing.JList<>();
        timeslotTextLabel = new javax.swing.JLabel();
        timeslotButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Table Reservation");

        restaurantTextLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        restaurantTextLabel.setText("Selected Restaurant: ");

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Number of Covers:");

        tableButton.setText("Find a table");

        cardnumTextEmail.setText("CardNum");

        phonenumTextLabel.setText("PhoneNum");

        dateLabel.setText("Date");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Table List:");

        jLabel14.setText("Will you want seperate tables?");

        jRadioButton10.setText("Yes");
        seperatetables.add(jRadioButton10);

        jRadioButton11.setSelected(true);
        jRadioButton11.setText("No");
        seperatetables.add(jRadioButton11);

        emailTextLabel.setText("E-mail");

        nameTextLabel.setText("Name");

        nameLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        nameLabel.setText("jLabel21");

        allergyLabel.setText("Allergies:");

        allergyGluten.setText("gluten");

        allergyDairy.setText("dairy");

        allergyFish.setText("fish");

        allergyShellfish.setText("shellfish");

        allergyPeanuts.setText("peanuts");

        allergySoya.setText("soya");

        userNameTextLabel.setText("Username");

        usernameLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        usernameLabel.setText("jLabel4");

        emailLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        emailLabel.setText("jLabel5");

        cardnumLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        cardnumLabel.setText("jLabel6");

        phonenumLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        phonenumLabel.setText("jLabel7");

        restaurantLabel.setText("jLabel2");

        loyaltyTextLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        loyaltyTextLabel.setText("Your Loyalty is:");

        tableList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(tableList);

        loyaltyLabel.setText("jLabel4");

        discountTextLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        discountTextLabel.setText("Your Special is:");

        discountLabel.setText("jLabel4");

        timeslotList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        timeslotList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        timeslotList.setToolTipText("");
        DefaultListModel listModel = new DefaultListModel();
        timeslotList.setModel(listModel );
        Calendar c = Calendar.getInstance();
        int year = c.get(Calendar.YEAR);  
        int month = c.get(Calendar.MONTH);   
        int date1 = c.get(Calendar.DATE);      

        for(int i=0;i<15;i++){
            int hour = 10 + i;
            String time = hour + ":00";
            String date = year + "/" + (month+1) + "/" + date1;
            listModel.addElement(date + " " + time);
        }
        jScrollPane1.setViewportView(timeslotList);

        timeslotTextLabel.setText("TimeSlot:");

        timeslotButton.setText("Verify Time");
        timeslotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeslotButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allergyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(restaurantTextLabel)
                                    .addComponent(discountTextLabel)
                                    .addComponent(nameTextLabel)
                                    .addComponent(userNameTextLabel)
                                    .addComponent(emailTextLabel)
                                    .addComponent(cardnumTextEmail)
                                    .addComponent(phonenumTextLabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(loyaltyLabel)
                                                .addComponent(restaurantLabel)
                                                .addComponent(discountLabel))
                                            .addComponent(phonenumLabel)
                                            .addComponent(cardnumLabel)
                                            .addComponent(emailLabel)
                                            .addComponent(usernameLabel)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(nameLabel))))
                            .addComponent(loyaltyTextLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(dateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(allergyPeanuts)
                                            .addComponent(allergyFish))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(allergyShellfish)
                                            .addComponent(allergySoya)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton11))
                                            .addComponent(numOfGuestsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(allergyGluten)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(cancelButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(allergyDairy)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeslotTextLabel)
                                    .addComponent(timeslotButton)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(restaurantTextLabel)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(numOfGuestsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restaurantLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(timeslotTextLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(timeslotButton)
                                .addGap(5, 5, 5))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton11))
                        .addGap(41, 41, 41)
                        .addComponent(dateLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tableButton)
                            .addComponent(loyaltyTextLabel)
                            .addComponent(loyaltyLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discountTextLabel)
                            .addComponent(discountLabel))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTextLabel)
                            .addComponent(nameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameTextLabel)
                            .addComponent(usernameLabel))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTextLabel)
                            .addComponent(emailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cardnumTextEmail)
                            .addComponent(cardnumLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phonenumTextLabel)
                            .addComponent(phonenumLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergyGluten)
                    .addComponent(allergyDairy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergyFish)
                    .addComponent(allergyShellfish))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergyPeanuts)
                    .addComponent(allergySoya))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(cancelButton))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void timeslotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeslotButtonActionPerformed
        // TODO add your handling code here:
        if(isFindATable == false){
            JOptionPane.showMessageDialog(null,"Please select a table first!");
        }
        else{
            JOptionPane.showMessageDialog(null,"Works!!");
            isFindATime = true;
        }
    }//GEN-LAST:event_timeslotButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        if(isFindATable == false || isFindATime == false ){
            JOptionPane.showMessageDialog(null,"Please set a table or a time slot");
        }
        else{
            // do booking on it.
        }
    }//GEN-LAST:event_confirmButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allergyDairy;
    private javax.swing.JRadioButton allergyFish;
    private javax.swing.JRadioButton allergyGluten;
    private javax.swing.JLabel allergyLabel;
    private javax.swing.JRadioButton allergyPeanuts;
    private javax.swing.JRadioButton allergyShellfish;
    private javax.swing.JRadioButton allergySoya;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cardnumLabel;
    private javax.swing.JLabel cardnumTextEmail;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JLabel discountTextLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailTextLabel;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel loyaltyLabel;
    private javax.swing.JLabel loyaltyTextLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameTextLabel;
    private javax.swing.JTextField numOfGuestsTextField;
    private javax.swing.JLabel phonenumLabel;
    private javax.swing.JLabel phonenumTextLabel;
    private javax.swing.ButtonGroup restaurant;
    private javax.swing.JLabel restaurantLabel;
    private javax.swing.JLabel restaurantTextLabel;
    private javax.swing.ButtonGroup seperatetables;
    private javax.swing.JButton tableButton;
    private javax.swing.JList<String> tableList;
    private javax.swing.ButtonGroup tables;
    private javax.swing.JButton timeslotButton;
    private javax.swing.JList<String> timeslotList;
    private javax.swing.JLabel timeslotTextLabel;
    private javax.swing.JLabel userNameTextLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the allergyDairy
     */
    public JRadioButton getAllergyDairy() {
        return allergyDairy;
    }


    /**
     * @return the allergyFish
     */
    public JRadioButton getAllergyFish() {
        return allergyFish;
    }


    /**
     * @return the allergyGluten
     */
    public JRadioButton getAllergyGluten() {
        return allergyGluten;
    }

   

    /**
     * @return the allergyPeanuts
     */
    public JRadioButton getAllergyPeanuts() {
        return allergyPeanuts;
    }


    /**
     * @return the allergyShellfish
     */
    public JRadioButton getAllergyShellfish() {
        return allergyShellfish;
    }


    /**
     * @return the allergySoya
     */
    public JRadioButton getAllergySoya() {
        return allergySoya;
    }


    /**
     * @return the cancelButton
     */
    public JButton getCancelButton() {
        return cancelButton;
    }


    /**
     * @return the cardNumEmail
     */
    public JLabel getCardNumEmail() {
        return cardnumTextEmail;
    }

    

    public JLabel getCardNumLabel() {
        return cardnumLabel;
    }


    /**
     * @return the confirmButton
     */
    public javax.swing.JButton getConfirmButton() {
        return confirmButton;
    }

  
    public JLabel getEmailLabel() {
        return emailLabel;
    }

    /**
     * @return the nameEditLabel
     */
    public JLabel getNameLabel() {
        return nameEditLabel;
    }



    /**
     * @return the phoneNumTextField
     */
    public JLabel getPhoneNumLabel() {
        return phonenumLabel;
    }

     

    /**
     * @return the tableButton
     */
    public JButton getTableButton() {
        return tableButton;
    }

    

    /**
     * @return the numOfGuestsTextField
     */
    public JTextField getNumOfGuestsTextField() {
        return numOfGuestsTextField;
    }



    /**
     * @return the jDateChooser
     */
    public JDateChooser getjDateChooser() {
        return jDateChooser;
    }

}
