/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Yiran Gao - 17083214
 */
public class ModifyReservationView extends javax.swing.JFrame {
    /*private int userid = mainmenu.fetchUserid();
    private String username = mainmenu.fetchUsername();
    private boolean isSearched = false;
    private boolean isVerified = false;*/
    /**
     * Creates new form modifyreservation
     */
    public ModifyReservationView() {
      /*  userid = mainmenu.fetchUserid();
        username = mainmenu.fetchUsername();*/
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        orderTextLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        orderidTextLabel = new javax.swing.JLabel();
        orderidTextField = new javax.swing.JTextField();
        usernameTextLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        orderinfoLabel = new javax.swing.JLabel();
        restaurantTextLabel = new javax.swing.JLabel();
        restaurantTextField = new javax.swing.JTextField();
        tabelTextLabel = new javax.swing.JLabel();
        tableTextField = new javax.swing.JTextField();
        dateTextLabel = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        emailTextLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        cardnumTextLabel = new javax.swing.JLabel();
        cardnumTextField = new javax.swing.JTextField();
        phonenumTextLabel = new javax.swing.JLabel();
        phonenumTextField = new javax.swing.JTextField();
        noteTextField = new javax.swing.JLabel();
        allergicTextField = new javax.swing.JTextField();
        verifyButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel1.setText("Modify Your Reservation");

        usernameLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        usernameLabel.setText("jLabel2");

        orderTextLabel.setText("Search Order:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        orderidTextLabel.setText("Order ID:");

        usernameTextLabel.setText("User Name:");

        orderinfoLabel.setText("userid,username,restaurant,tableSelected,date,email,cardNum,phoneNum,note");

        restaurantTextLabel.setText("Restaurant:");

        tabelTextLabel.setText("Table");

        dateTextLabel.setText("Date");

        emailTextLabel.setText("E-mail");

        cardnumTextLabel.setText("CardNum");

        phonenumTextLabel.setText("PhoneNum");

        noteTextField.setText("Note");

        allergicTextField.setText("jTextField9");

        verifyButton.setText("Verify");
        verifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Confirm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(orderinfoLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(allergicTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(usernameLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(orderTextLabel)
                                .addGap(18, 18, 18)
                                .addComponent(orderidTextLabel)
                                .addGap(18, 18, 18)
                                .addComponent(orderidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(usernameTextLabel)
                                .addGap(18, 18, 18)
                                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchButton)))
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verifyButton)
                            .addComponent(noteTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cardnumTextLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cardnumTextField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(restaurantTextLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(restaurantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tabelTextLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(tableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phonenumTextLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(phonenumTextField)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateTextLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailTextLabel)
                                .addGap(18, 18, 18)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jButton3)
                .addGap(189, 189, 189)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(usernameLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderTextLabel)
                    .addComponent(searchButton)
                    .addComponent(orderidTextLabel)
                    .addComponent(orderidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTextLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderinfoLabel)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantTextLabel)
                    .addComponent(restaurantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabelTextLabel)
                    .addComponent(tableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTextLabel)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardnumTextLabel)
                    .addComponent(cardnumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumTextLabel)
                    .addComponent(phonenumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(noteTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allergicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(verifyButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        
        /*
        if(mainmenu.fetchUsertype() == 1){
            if((jTextField2.getText().equals("")&&jTextField1.getText()!="")||(jTextField1.getText()!=""&&jTextField2.getText().equals(username))){
                CUSTOMER behaviour
                 int orderid = Integer.parseInt(jTextField2.getText();
                    REQUEST API
                    return boolean getOrderById(int orderid,string username);  if has this order, true else false;
                    return string getorderToString(int orderid);
                    example should like this userid,username,restaurant,tableSelected,date,email,cardNum,phoneNum,note
                    and i will split up with comma, and push it to a arraylist
                    then using arraylist like seperate order info to setText() to each textfield.
                
            }else{
                JOptionPane.showMessageDialog(null,"Incorrect username!");
            }
        }else{
            
                return boolean getOrderById(int orderid,string username); 
                if have this order
                getorderToString(int orderid);
                also filled the splited string to different jTextField setText();
            
        }*/
    }//GEN-LAST:event_searchButtonActionPerformed

    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed
        // TODO add your handling code here:
        /*
            REQUEST API
            
            after people changed, it will have verify api:
            isVerified = return boolean verify(restaurant,tableSelected,date);
            
            REQUEST API
            
            if(isVerified){
                changeBooking(orderid,userid,username,restaurant,tableSelected,date,email,cardNum,phoneNum,note);
            }else{
                show an error
            }
        */
    }//GEN-LAST:event_verifyButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editorld>
        //</editor-fold>
        //</editorld>
        //</editor-fold>
        //</editorld>
        //</editor-fold>
        //</editorld>
        //</editor-fold>
        //</editorld>
        //</editor-fold>
        //</editorld>
        //</editor-fold>
        //</editorld>
        //</editor-fold>
        //</editorld>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyReservationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField allergicTextField;
    private javax.swing.JTextField cardnumTextField;
    private javax.swing.JLabel cardnumTextLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel dateTextLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel emailTextLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel noteTextField;
    private javax.swing.JLabel orderTextLabel;
    private javax.swing.JTextField orderidTextField;
    private javax.swing.JLabel orderidTextLabel;
    private javax.swing.JLabel orderinfoLabel;
    private javax.swing.JTextField phonenumTextField;
    private javax.swing.JLabel phonenumTextLabel;
    private javax.swing.JTextField restaurantTextField;
    private javax.swing.JLabel restaurantTextLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel tabelTextLabel;
    private javax.swing.JTextField tableTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JLabel usernameTextLabel;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables
}
